# Generated by Django 6.1.1 on 2026-09-03 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección / Ubicación')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True, verbose_name='¿Obra activa?')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('trabajador', 'Trabajador'), ('supervisor', 'Supervisor'), ('gerencia', 'Gerencia')], default='trabajador', max_length=20)),
                ('obra_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='marvelec_app.obra', verbose_name='Obra asignada')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Trabajador',
                'verbose_name_plural': 'Perfiles de Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='ReporteAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('foto_llegada', models.ImageField(blank=True, null=True, upload_to='reportes/llegada/')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentarios / consultas')),
                ('total_puntos', models.PositiveIntegerField(default=0, editable=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='marvelec_app.obra')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_avance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Avance',
                'verbose_name_plural': 'Reportes de Avance',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_punto', models.CharField(choices=[('red', 'Punto de Red'), ('fuerza', 'Punto de Fuerza'), ('iluminacion', 'Punto de Iluminación')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='marvelec_app.reporteavance')),
            ],
            options={
                'verbose_name': 'Registro de Puntos',
                'verbose_name_plural': 'Registros de Puntos',
            },
        ),
        migrations.CreateModel(
            name='Subetapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subetapas', to='marvelec_app.obra')),
            ],
            options={
                'verbose_name': 'Subetapa',
                'verbose_name_plural': 'Subetapas',
                'ordering': ['obra__nombre', 'nombre'],
                'unique_together': {('obra', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='subetapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='marvelec_app.subetapa'),
        ),
    ]
