# Generated by Django 5.2.17 on 2026-09-27 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvelec_app', '0002_suscripcionpush'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiarioEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatarios', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Resumen diario enviado',
                'verbose_name_plural': 'Resúmenes diarios enviados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='comentario_revision',
            field=models.TextField(blank=True, verbose_name='Observación del supervisor'),
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='enviado_offline',
            field=models.BooleanField(default=False, verbose_name='¿Enviado sin conexión?'),
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('observado', 'Observado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporteavance',
            name='uuid_cliente',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reporteavance',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuevo_reporte', 'Nuevo reporte'), ('reporte_corregido', 'Reporte corregido'), ('reporte_aprobado', 'Reporte aprobado'), ('reporte_observado', 'Reporte observado'), ('resumen_diario', 'Resumen diario')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='marvelec_app.reporteavance')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='marvelec_ap_usuario_b16bff_idx')],
            },
        ),
    ]
